added missing license statements
moveit/moveit_kinematics_tests pull request #14
Opened 2017-07-21 18:30 UTC by jrgnicho

Fix for issue #8

2017-07-22 22:16 UTC, davetcoleman requested changes

2017-07-22 22:16 UTC, davetcoleman commented on kinematics_tests_support/package.xml
> -  <!-- <url type="website">http://wiki.ros.org/kinematics_tests_support</url> -->
do you mind adding this or something similar:

```
  <url type="website">http://moveit.ros.org</url>
  <url type="bugtracker">https://github.com/ros-planning/moveit/issues</url>
  <url type="repository">https://github.com/ros-planning/moveit</url>
```

?

2017-07-22 22:16 UTC, davetcoleman commented on kinematics_base_test/src/test_kinematics_plugin.cpp
> + *  Copyright (c) 2015, Southwest Research Institute
Your call - but do you want this to be 2017 instead?

2017-07-22 22:16 UTC, davetcoleman commented on kuka_kr210_manipulator_ik_plugin/package.xml
> +  <author email="jrgnichodevel@gmail.com">Jorge Nicho</author>
same here for website address

2017-07-22 22:16 UTC, davetcoleman commented on motoman_sia20d_ikfast_manipulator_plugin/package.xml
> +  <author email="jrgnichodevel@gmail.com">Jorge Nicho</author>
same here for website address

2017-07-23 19:48 UTC, jrgnicho commented on kinematics_base_test/src/test_kinematics_plugin.cpp
> + *  Copyright (c) 2015, Southwest Research Institute
The file was created in 2015 if I recall correctly, I'm not sure if there are any rules on this but I went on date of creation.

2017-07-31 16:00 UTC, jrgnicho commented
@davetcoleman sorry for the delay on this, just made the changes you requested.

2017-08-01 14:48 UTC, davetcoleman approved these changes

2017-08-01 14:49 UTC, davetcoleman commented
@jrgnicho the CI failed because of broken tests, I think from the previous PR. This PR is fine to merge since it does not change code but I'd really appreciate you looking at the broken test.

2017-08-01 14:50 UTC, merged

2017-08-01 14:50 UTC, jrgnicho commented
@davetcoleman thanks for approving, I'll look into that.