Created motoman_mh5_ikfast_manipulator_plugin
moveit/moveit_kinematics_tests pull request #9
Opened 2017-06-16 22:16 UTC by nsnitish

IKfast plugin for motoman mh5 as a part of issue #172. test.cpp included in the repository tests if one of the solutions created IKfast is the true solution. 

TODO: Need to test it with moveit.

2017-06-16 22:28 UTC, jrgnicho requested changes
There is a duplicate file **motoman_mh5_ikfast_manipulator_plugin/src/motoman_mh5_manipulator_ikfast_solver.cpp** in the **src/test** directory.
Also, I'm not sure why the solver code is over 20K lines of code.

2017-06-16 22:28 UTC, jrgnicho commented on motoman_mh5_ikfast_manipulator_plugin/package.xml
> +  <license>TODO</license>
I know this came from the automatic gen tool but could you set the license to BSD and clean up the file a bit?

2017-06-17 03:54 UTC, shaun-edwards commented
@nsnitish, please also submit the ikfast solution to the motoman repo as well.  See [here](http://wiki.ros.org/Industrial/Tutorials/SuggestedPackageLayoutNewRepositories) for instructions, as well as the [fanuc repo](https://github.com/ros-industrial/fanuc) for an example of how to include the ikfast solver.

2017-06-17 03:58 UTC, shaun-edwards commented
@nsnitish, I cannot find the place where you test the item requested in the linked issue.  Specifically:
> Create a test program that verifies the resulting solution returns the nearest IK solution in joint space.

Please point me to the specific code line(s) that perform this test.

2017-06-17 08:35 UTC, gavanderhoorn commented
@shaun-edwards wrote:
> @nsnitish, please also submit the ikfast solution to the motoman repo as well.  

I'd rather have this in one place. Duplication is something to be avoided.

@nsnitish: is there any specific reason why you want the plugin to be added to this repository?

2017-06-19 04:59 UTC, shaun-edwards commented
@nsnitish, now that you have addressed the smart pointer issue, we can add the test I'm interested in.  Basically, use the `getIK` and `getMultipleIK` tests as an example [here](https://github.com/ros-planning/moveit_kinematics_tests/blob/kinetic-devel/kinematics_base_test/src/test_kinematics_plugin.cpp#L355-L495).  For a Cartesian pose, call both versions of the `getPositionIK` (one returns one solution, the other returns many).  Then iterate through the multiple IK solutions and make certain that none are closer than the one, single solution.  

You will likely need to iterate through many Cartesian poses to fully test this.  

Also, this test should run fine for non-ikfast solvers since they should return the same, single answer for both calls of `getPositionIK`.

2017-06-19 23:20 UTC, jrgnicho commented
I agree with @shaun-edwards with setting up a test that checks that the solution returned by  **getPositionIK** is indeed is the closest to the seed.  This test should apply to all plugins if done correctly (KDL, IKfast, tracIK, etc.)
I think @gavanderhoorn suggestion of avoiding duplication is valid, in fact I do think that the motoman_mh5 ikfast code should live in that robot's repo and your test code could have **moveit_kinematic_tests** as a dependency

2017-06-23 18:54 UTC, nsnitish commented
Closing for now. Will add new PR related to above comments

2017-06-23 18:54 UTC, closed without merging